site_name: HighZ
site_url: https://highz-fic.github.io
docs_dir: 'src'

markdown_extensions:
- extra  # allow markdown in <div markdown="1">
- fenced_code  # GitHub style code blocks, e.g. ```python, see https://highlightjs.readthedocs.org/en/latest/css-classes-reference.html for a list of languages
- footnotes
- attr_list  # Allow us to add link attributes

nav:
- Home: index.md
- Motivation: mission.md
- Computing:
  - 'Scientific Computing': cont-fmr.md
  - 'Scientific Machine Learning': acceleration.md
  - 'Scalable Open-Source Frameworks': gts.md
- Physics:
  - 'Magnetic Reconnection': reconnection.md
#- Publications: publications.md
- Calendar: calender.md
- Opening: opening.md
- News: news.md
- About: about.md

theme:
  name: mkdocs  # required. Can be anything as long as custom_dir is set correctly below
  custom_dir: template
  features:
    - search.suggest

extra:
  include_next_prev: false  # turn off next/previous buttons

plugins:
  - search
  - macros:
      include_dir: "src/"
  - exclude-search:
      exclude:
        # List of pages that will not be searched
        - index.md
